## Practice Questions for numpy

Part 1 - Numpy

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [1]:
# Numpy Question 1: 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Defining two 4x4 numpy arrays A and B (has to be 4x4 to do both the horizontal and vertical stacks)

A = iris_2d[17:21, :] 
B = iris_2d[47:51, :]  

print("Array A:\n", A,"\n Shape:", A.shape)
print("\nArray B:\n", B,"\n Shape:", B.shape)

# Vertical stack
v_stack = np.vstack((A, B))

# Horizontal stack
h_stack = np.hstack((A, B))

print("\nVertical Stack:\n", v_stack,"\n Shape:", v_stack.shape)
print("\nHorizontal Stack:\n", h_stack, "\n Shape:", h_stack.shape)


Array A:
 [[5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]] 
 Shape: (4, 4)

Array B:
 [[4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]] 
 Shape: (4, 4)

Vertical Stack:
 [[5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]] 
 Shape: (8, 4)

Horizontal Stack:
 [[5.1 3.5 1.4 0.3 4.6 3.2 1.4 0.2]
 [5.7 3.8 1.7 0.3 5.3 3.7 1.5 0.2]
 [5.1 3.8 1.5 0.3 5.  3.3 1.4 0.2]
 [5.4 3.4 1.7 0.2 7.  3.2 4.7 1.4]] 
 Shape: (4, 8)


In [2]:
#Numpy Question 2: Find common elements between A and B. [Hint : Intersection of two sets]

# Empty list that will be filled with common elements
common_elements = []

#Convert A and B into lists using flatten function
A_elements=A.flatten()
B_elements=B.flatten()

print("Elements of A:", A_elements)
print("Elements of B", B_elements)

# Iterating using for loops to find common elements
for a in A_elements:
    for b in B_elements:
        if (a == b) and (a not in common_elements):
            common_elements.append(a)

print("Common elements between A and B:", np.sort(common_elements))

Elements of A: [5.1 3.5 1.4 0.3 5.7 3.8 1.7 0.3 5.1 3.8 1.5 0.3 5.4 3.4 1.7 0.2]
Elements of B [4.6 3.2 1.4 0.2 5.3 3.7 1.5 0.2 5.  3.3 1.4 0.2 7.  3.2 4.7 1.4]
Common elements between A and B: [0.2 1.4 1.5]


In [3]:
#Numpy Question 3: Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
# Use np.where to find elements between 5 and 10
boolean_result = np.where((A >= 5) & (A <= 10))

# Extracting the values based on the indices returned by np.where
result = A[boolean_result]
print("Elements between 5 and 10 in array A are:", np.sort(result))

Elements between 5 and 10 in array A are: [5.1 5.1 5.4 5.7]


In [4]:
#Numpy Question 4:Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Boolean conditions for filtering Petal length > 1.5 and Sepal length < 5.0
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print("Filtered rows where petal length > 1.5 and sepal length < 5.0:")
print(filtered_rows)
print("Total number of rows:", len(iris_2d))
print("There are", len(filtered_rows), "that fit the conditions asked in the question.")

Filtered rows where petal length > 1.5 and sepal length < 5.0:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
Total number of rows: 150
There are 6 that fit the conditions asked in the question.


## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [5]:
#Pandas Question 1: From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_filtered = df.loc[::20,['Manufacturer','Model', 'Type']]

df_filtered

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [ ]:
#Pandas Question 2: Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

#Calculate mean min and max prices
mean_minprice=df['Min.Price'].mean()
mean_maxprice=df['Max.Price'].mean()

#Display the obtained values:
print("Mean Minimum Price is: ",round(mean_minprice,1))
print("Mean Maximum Price is: ",round(mean_maxprice,1))

#The dataframe before missing (NaN) values are filled
display(df)

#Lambda functions to fill missing values for the respective columns (rounded to 1 digit after decimal)
min_apply = lambda x: round(mean_minprice, 1) if pd.isna(x) else round(x, 1)
max_apply = lambda x: round(mean_maxprice, 1) if pd.isna(x) else round(x, 1)

#Apply Lambda function of the respective columns
df['Min.Price'] = df['Min.Price'].apply(min_apply)
df['Max.Price'] = df['Max.Price'].apply(max_apply)

#Final dataframe with missing values filled
display(df)

Mean Minimum Price is:  17.1
Mean Maximum Price is:  21.5


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize       17.1   37.7       44.6      19.0   
4           BMW     535i  Midsize       17.1   30.0       21.5      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [ ]:
#Pandas Question 3: How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

#Add column to df to display the sum of the original rows
df['Sum'] = df.sum(axis=1)

display(df)

# List to store the rows with sum > 100
sum100 = []

# Loop through each row in the DataFrame
for i in range(0,len(df)):
    # Calculate the sum of the rows (excluding the cell corresponding to the newly added Sum column)
    row_sum = sum(df.loc[i,0:3])
    
    # If the row sum is greater than 100, add the row to the list
    if row_sum > 100:
        sum100.append(i)

# Convert the list of rows back to a DataFrame
result_df = pd.DataFrame(sum100)
result_df.rename(columns={0: 'row'}, inplace=True)

# Display the result DataFrame 
# Note: This df will display the index values starting from 0, if we want to assume rows start from 1, the code can be changed to append (i+1)
display(result_df)

0   1   2   3  Sum
0   32  17  37  26  112
1   31  31  12  20   94
2   16  12  23  19   70
3   20  31  27  33  111
4   36  30  20  31  117
5   24  17  35  21   97
6   31  12  23  13   79
7   34  16  12  23   85
8   29  18  29  37  113
9   38  12  28  38  116
10  25  36  33  32  126
11  25  15  19  29   88
12  22  25  15  21   83
13  31  14  38  33  116
14  25  19  10  28   82

row
0    0
1    3
2    4
3    8
4    9
5   10
6   13